name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: |
        python train.py
    
    - name: Run tests
      run: |
        python -m pytest test_model.py -v -s
        
    - name: Upload trained model
      uses: actions/upload-artifact@v3
      with:
        name: mnist-model
        path: models/*.pth
        if-no-files-found: error  # Fail if no model was saved
        retention-days: 14  # Keep artifacts for 14 days